Resources:
    Function:
        Type: AWS::Serverless::Function
        Properties:
            Timeout: 300
            MemorySize: 128
            Handler: handler
            CodeUri: /Users/daniil.maslov/Projects/Go/awesomeProject/lambda_inside_directory
            Runtime: go1.x
